spring:
  jpa:
    database: POSTGRESQL

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  flyway:
    locations: classpath:db/migration
    enabled: true


currency:
  api-key: "8a77e4eece4941a399336c741bc7cbf4"
  url: "https://api.twelvedata.com/time_series"

