spring:
  jpa:
    database: POSTGRESQL

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  flyway:
    locations: classpath:db/migration
    enabled: true


currency:
  api-key: ${12DATA_API_KEY}
  url: "https://api.twelvedata.com/time_series"
